<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MantenimientoTextil.Infraestructura.Access</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.OleDb" Version="8.0.0" />
    <ProjectReference Include="..\Aplicacion\Aplicacion.csproj" />
  </ItemGroup>
</Project>
